export const NEW_CAROUSEL_REQUEST = "NEW_CAROUSEL_REQUEST";
export const NEW_CAROUSEL_SUCCESS = "NEW_CAROUSEL_SUCCESS";
export const NEW_CAROUSEL_FAIL = "NEW_CAROUSEL_FAIL";


export const CLEAR_ERROR = "CLEAR_ERROR";    