export const GET_GOVERNING_REQUEST = "GET_GOVERNING_REQUEST";
export const GET_GOVERNING_SUCCESS = "GET_GOVERNING_SUCCESS";
export const GET_GOVERNING_FAIL = "GET_GOVERNING_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";