export const GET_GRIEVANCE_REQUEST = "GET_GRIEVANCE_REQUEST";
export const GET_GRIEVANCE_SUCCESS = "GET_GRIEVANCE_SUCCESS";
export const GET_GRIEVANCE_FAIL = "GET_GRIEVANCE_FAIL";

export const SUBMIT_FORM_REQUEST = 'SUBMIT_FORM_REQUEST';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAIL= 'SUBMIT_FORM_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";