export const GET_OTHER_REQUEST = "GET_OTHER_REQUEST";
export const GET_OTHER_SUCCESS = "GET_OTHER_SUCCESS";
export const GET_OTHER_FAIL = "GET_OTHER_FAIL";

export const GET_ANNOUNCEMENT_REQUEST = "GET_ANNOUNCEMENT_REQUEST";
export const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
export const GET_ANNOUNCEMENT_FAIL = "GET_ANNOUNCEMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"