export const GET_ADMIN_ABOUT_REQUEST = "GET_ADMIN_ABOUT_REQUEST";
export const GET_ADMIN_ABOUT_SUCCESS = "GET_ADMIN_ABOUT_SUCCESS";
export const GET_ADMIN_ABOUT_FAIL = "GET_ADMIN_ABOUT_FAIL";

export const ADD_ABOUTHEADER_ABOUT_REQUEST = "ADD_ABOUTHEADER_ABOUT_REQUEST";
export const ADD_ABOUTHEADER_ABOUT_SUCCESS = "ADD_ABOUTHEADER_ABOUT_SUCCESS";
export const ADD_ABOUTHEADER_ABOUT_FAIL = "ADD_ABOUTHEADER_ABOUT_FAIL";
export const ADD_ABOUTHEADER_ABOUT_RESET = "ADD_ABOUTHEADER_ABOUT_RESET";

export const ADD_IMAGE_ABOUT_REQUEST = "ADD_IMAGE_ABOUT_REQUEST";
export const ADD_IMAGE_ABOUT_SUCCESS = "ADD_IMAGE_ABOUT_SUCCESS";
export const ADD_IMAGE_ABOUT_FAIL = "ADD_IMAGE_ABOUT_FAIL";
export const ADD_IMAGE_ABOUT_RESET = "ADD_IMAGE_ABOUT_RESET";

export const ADD_VALUES_ABOUT_REQUEST = "ADD_VALUES_ABOUT_REQUEST";
export const ADD_VALUES_ABOUT_SUCCESS = "ADD_VALUES_ABOUT_SUCCESS";
export const ADD_VALUES_ABOUT_FAIL = "ADD_VALUES_VALUES_FAIL";
export const ADD_VALUES_ABOUT_RESET = "ADD_VALUES_ABOUT_RESET";

export const   UPDATE_VALUES_ABOUT_REQUEST = "  UPDATE_VALUES_ABOUT_REQUEST";
export const   UPDATE_VALUES_ABOUT_SUCCESS = "  UPDATE_VALUES_ABOUT_SUCCESS";
export const   UPDATE_VALUES_ABOUT_FAIL = " UPDATE_VALUES_ABOUT_FAIL";
export const   UPDATE_VALUES_ABOUT_RESET = "UPDATE_VALUES_ABOUT_RESET";

export const ADD_INVOLVED_ABOUT_REQUEST = "ADINVOLVED_ABOUT_REQUEST";
export const ADD_INVOLVED_ABOUT_SUCCESS = "ADINVOLVED_ABOUT_SUCCESS";
export const ADD_INVOLVED_ABOUT_FAIL = "AINVOLVED_VALUES_FAIL";
export const ADD_INVOLVED_ABOUT_RESET = "ADD_INVOLVED_ABOUT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";