export const GET_ADMIN_ABOUT_REQUEST = "GET_ADMIN_ABOUT_REQUEST";
export const GET_ADMIN_ABOUT_SUCCESS = "GET_ADMIN_ABOUT_SUCCESS";
export const GET_ADMIN_ABOUT_FAIL = "GET_ADMIN_ABOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";