export const GET_ADMIN_FORM_REQUEST = "GET_ADMIN_FORM_REQUEST";
export const GET_ADMIN_FORM_SUCCESS = "GET_ADMIN_FORM_SUCCESS";
export const GET_ADMIN_FORM_FAIL = "GET_ADMIN_FORM_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";