export const GET_ADMIN_GALLERY_REQUEST = "GET_ADMIN_GALLERY_REQUEST";
export const GET_ADMIN_GALLERY_SUCCESS = "GET_ADMIN_GALLERY_SUCCESS";
export const GET_ADMIN_GALLERY_FAIL = "GET_ADMIN_GALLERY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";