export const GET_ADMIN_GRIEVANCE_REQUEST = "GET_ADMIN_GRIEVANCE_REQUEST";
export const GET_ADMIN_GRIEVANCE_SUCCESS = "GET_ADMIN_GRIEVANCE_SUCCESS";
export const GET_ADMIN_GRIEVANCE_FAIL = "GET_GRIEVANCE_GRIEVANCE_FAIL";

export const ADD_GRIEVANCEHEADER_GRIEVANCE_REQUEST = "ADD_GRIEVANCEHEADER_GRIEVANCE_REQUEST";
export const ADD_GRIEVANCEHEADER_GRIEVANCE_SUCCESS = "ADD_GRIEVANCEHEADER_GRIEVANCE_SUCCESS";
export const ADD_GRIEVANCEHEADER_GRIEVANCE_FAIL = "ADD_GRIEVANCEHEADER_GRIEVANCE_FAIL";
export const ADD_GRIEVANCEHEADER_GRIEVANCE_RESET = "ADD_GRIEVANCEHEADER_GRIEVANCE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";