export const GET_ADMIN_HOME_REQUEST = "GET_ADMIN_HOME_REQUEST";
export const GET_ADMIN_HOME_SUCCESS = "GET_ADMIN_HOME_SUCCESS";
export const GET_ADMIN_HOME_FAIL = "GET_ADMIN_HOME_FAIL";

export const ADD_HOMEHEADER_HOME_REQUEST = "ADD_HOMEHEADER_HOME_REQUEST";
export const ADD_HOMEHEADER_HOME_SUCCESS = "ADD_HOMEHEADER_HOME_SUCCESS";
export const ADD_HOMEHEADER_HOME_FAIL = "ADD_HOMEHEADER_HOME_FAIL";
export const ADD_HOMEHEADER_HOME_RESET = "ADD_HOMEHEADER_HOME_RESET";

export const ADD_HIGHTLIGHT_HOME_REQUEST = "ADD_HIGHTLIGHT_HOME_REQUEST";
export const ADD_HIGHTLIGHT_HOME_SUCCESS = "ADD_HIGHTLIGHT_HOME_SUCCESS";
export const ADD_HIGHTLIGHT_HOME_FAIL = "ADD_HIGHTLIGHT_HOME_FAIL";
export const ADD_HIGHTLIGHT_HOME_RESET = "ADD_HIGHTLIGHT_HOME_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";