export const GET_ADMIN_SERVICES_REQUEST = "GET_ADMIN_SERVICES_REQUEST";
export const GET_ADMIN_SERVICES_SUCCESS = "GET_ADMIN_SERVICES_SUCCESS";
export const GET_ADMIN_SERVICES_FAIL = "GET_ADMIN_SERVICES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";